# Azure Pipelines

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install --upgrade tox tox-venv
      pip freeze --all
      env
    displayName: 'Install prereqs'

  - script: |
      # update egg_info based on setup.py in checkout
      python bootstrap.py
      ls setuptools.egg-info
      #"! grep pyc setuptools.egg-info/SOURCES.txt"
    displayName: Update egg_info

  - script: |
      pip install pytest
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: false # disable for a moment; was succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  condition: false # disable for starters
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
